### ISSUE TITLE
Had to run "olkc profile" first

### ISSUE THREAD

**Issue by morganzhh** [xeric/alfred-outlook#2]
Thanks, this is an amazing workflow.

After installing it didn't run well with zero configuration. From the debug message, figured out outlook ``profile`` must be set first because my default profile name is not ``Main Profile``

It would be nice to add this reminder in README.

Thanks,
Morgan.

**Comment by xeric** [comment]
Hi @morganzhh you are right, by default value is Main Profile because by default Outlook use Main Profile as your default account profile, if you are not using default one, workflow will tell you that you must figure out which one is your profile.
There are some reasons that I did not select a profile automatically when default one (Main Profile) is not existing:
- Some user they have multiple accounts configured and I did not know which one is default.
- To check profile every time when workflow executed has performance consideration, if user is using default one, there's no configuration for profile in data store, I have to call file API to check if default profile folder is exists or not. 

This is still 2-8 principle, 80% users are using Outlook which just have one account and default one, function must cover their scenarios smoothly and quickly but still provide a way to resolve 20% other users' cases.

**Comment by morganzhh** [comment]
Hi @xeric,

Thanks for the explanation. I totally agree with you on the 2-8 principle. However, if we can improve that "20% is not working" to "20% is working but not working as expected", it would be great. Having said that, I would suggest picking one profile at the beginning as the default profile in the beginning if the data store has no configuration, then store it to the data store. Decide which one is the default profile is tricky but we can start with ``Main Profile`` first then random or the first profile in the directory.

So with zero-touch configuration, a user always gets the result from the mail searching, if it's not the right mailbox/profile, he then might be thinking about changing the profile, makes sense?

Thanks,
Morgan.

**Comment by xeric** [comment]
@morganzhh yes, that's why I've labeled this ticket as enhancement, there's only 1 scenario I'm still struggling on how to make it perfect, there's a case that user has multiple profiles, and only one of them is workable (others have no real mail in them), if I choose a profile randomly e.g. by alphabet - which is empty, it will make this user confused when first time search something since workflow just tell him found nothing.
Maybe I just give up multiple profiles' case and if I found multiple profiles, popup hint like now.

**Comment by xeric** [comment]
@morganzhh I release 0.1.4 now when first time this workflow launched, it will check all sub folders of profile, and compare file size of profile data, set the largest one as default profile into configuration. 

https://github.com/xeric/alfred-outlook/releases/tag/0.1.4

**Comment by morganzhh** [comment]
Excellent, again, thanks a lot for the amazing job.
