### ISSUE TITLE
no content preview

### ISSUE THREAD

**Issue by tritor100** [xeric/alfred-outlook#6]
Hi,

using version 0.15 and cannot see and preview of email messages.
<img width="571" alt="Screenshot 2019-08-27 at 15 30 04" src="https://user-images.githubusercontent.com/54586163/63775701-304b9500-c8e0-11e9-8d8d-09c5800b7212.png">

not sure if I did something wrong in the config.

**Comment by xeric** [comment]
@tritor100 I did not see such issue in my local, this preview content is came from outlook db records, preview column data is not managed by this plugin, it automatically filled by outlook app, I'm thinking maybe it is not updated due to some reason, for example, cache issue:
https://answers.microsoft.com/en-us/msoffice/forum/all/outlook-for-mac-2016-preview-not-updating/2c50763c-3723-4956-855d-6a9c28c0e754
Could you try to open your outlook and rebuild cache to check again?
If you still can't see preview content, I can send you a debug version to see what happens in backend when this plugin running.

**Comment by xeric** [comment]
No feedback for over 1 month, close.
